# Site settings
name: 谭浩的技术博客
email: realtanhao@gmail.com
author: Tanhao
url: https://ietanhao.github.io
resume_site: https://ietanhao.github.io/me/
github: https://github.com/ietanhao
baseurl: ""  #根目录
description: 今天的你比昨天更博学了吗？
motto: 读万卷书，行万里路
#motto: 如果生活欺骗了你，不要悲伤，不要哭泣。
banner: 日拱一卒无有尽，功不唐捐终入海
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: ietanhao
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : tanhao
